[package]
name = "wr_apped"
authors = ["Tim Fischer <fischeti@iis.ee.ethz.ch>"]
repository = "https://github.com/fischeti/WRapped"
description = "Wrapped but for Weekly Reports"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
toml = "0.8.8"
